#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[344] =
    {   0,
        0,    0,   90,   89,   38,   39,   88,   56,   89,   28,
       84,   53,   57,   85,   41,   42,   51,   49,   48,   50,
       47,   52,   34,   34,    5,   40,   59,   70,   60,   61,
       82,   86,   86,   43,   44,   67,   83,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   45,   66,   46,   58,    1,    1,   88,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,   38,   65,    0,   37,
        0,   30,   29,    0,   69,   76,    0,    0,   71,   54,
        0,   35,   73,   55,   33,   74,   78,   35,   27,    0,
       72,   87,   34,    0,    0,    3,    4,   77,   79,   80,
       62,   64,   63,   81,    0,   86,   86,    0,    0,   86,
       86,   86,   86,   86,   86,   86,    6,   20,   86,   86,
       86,   18,   86,   86,   86,   86,   86,   75,   68,    1,
        1,    0,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    0,    0,   31,   87,   87,    0,
       35,   32,    2,   17,   86,   86,   86,   86,   86,   86,
       13,   24,   19,   86,   86,   86,   14,   21,   16,   86,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    0,    0,   86,   10,
       86,   86,    7,   86,   36,   86,   22,   86,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        0,    0,   12,   15,   86,   23,   86,    8,    1,    1,
        1,    1,    1,    1,    1,    1,    0,    0,   86,    9,
        1,    1,    1,    1,   26,    0,   11,    1,    1,    1,
       25,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   30,   29,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       33,   34,   35,   36,   31,   37,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   31,   47,   48,   49,   50,
       51,   52,   31,   53,   54,   55,   56,   57,   58,   59,
       60,   31,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    4,    5,
        5,    4,    1,    1,    6,    1,    1,    1,    7,    7,
        4,    4,    1,    1,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[353] =
    {   0,
        0,   64,  862,  863,  859,  863,  863,  835,  123,   89,
      863,  863,  121,  825,  863,  863,  833,  118,  863,  127,
      129,  115,  138,  142,  142,  863,  149,  832,  129,  863,
      863,  156,  179,  863,  863,  863,  863,  167,  172,  183,
      187,  191,  211,  215,  221,  200,  210,  222,  225,  229,
      244,  863,  107,  863,  863,    0,  854,  851,  829,  212,
      242,    0,    0,  171,  216,    0,    0,  828,  272,    0,
      281,  150,  289,  332,  336,  290,    0,  230,  827,  157,
        0,    0,  373,  217,    0,    0,    0,    0,  801,  796,
      808,  782,  773,  206,  202,  266,  763,  752,  743,  737,

      752,  744,    0,  117,    0,    0,  784,  863,  290,  863,
      782,  863,  735,  741,  863,  863,  292,  211,  863,  863,
      249,  340,  863,  863,  347,  863,  863,  343,  291,  753,
      863,  377,  416,  366,    0,  863,  350,  863,  863,  863,
      863,  863,  863,  863,  416,  350,  401,  317,  731,  404,
      405,  411,  421,  425,  432,  431,  435,  447,  451,  454,
      466,  455,  462,  474,  477,  485,  486,  863,  863,    0,
      761,  755,    0,  493,    0,  376,    0,  707,  715,    0,
        0,  536,  404,    0,    0,  389,  525,    0,    0,  530,
        0,    0,  532,  365,  727,    0,  555,  536,  433,  596,

        0,  449,    0,    0,    0,    0,    0,    0,    0,  501,
        0,    0,  555,  616,  698,  688,  440,  685,  666,  670,
      664,    0,    0,  666,  656,  661,    0,  645,  299,  645,
      624,  622,    0,    0,  614,  622,  863,  560,  602,  543,
      548,    0,  637,  493,  590,  591,  592,  593,  613,  602,
      614,  616,  622,  623,  625,  644,  637,  645,  646,  656,
      605,  605,    0,    0,    0,  570,  669,  693,  596,    0,
      554,  546,  543,  539,  531,  517,    0,    0,    0,  517,
      480,  487,    0,    0,    0,  473,  465,  443,  668,  647,
      654,  670,  687,  699,  689,  706,  691,  710,  427,  428,

      404,    0,  399,  384,    0,  358,    0,  336,    0,  329,
      272,  267,  713,  716,  720,  722,  732,  736,  238,  248,
        0,    0,  236,    0,  229,    0,  216,  220,  742,  743,
      171,  180,  140,    0,  863,  123,  744,    0,  109,    0,
      863,    0,  863,  800,  807,  811,  815,  822,  829,  836,
      840,  843
    } ;

static yyconst flex_int16_t yy_def[353] =
    {   0,
      343,  343,  343,  343,  343,  343,  343,  343,  344,  343,
      343,  343,  343,  345,  343,  343,  343,  343,  343,  343,
      343,  346,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  347,  347,  343,  343,  343,  343,  347,  347,  347,
      347,  347,  347,  347,  347,   45,   45,   45,   45,   45,
       45,  343,  343,  343,  343,  348,  348,  348,  348,  349,
      348,  348,  348,  348,  350,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,   83,  348,  348,  348,  348,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,  348,  348,  348,  348,  343,  343,  344,  343,
      344,  343,  343,  343,  343,  343,  345,  345,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  346,  343,
      343,  351,  343,  343,  352,  343,  346,  343,  343,  343,
      343,  343,  343,  343,  346,   45,   45,  344,  345,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,  343,  343,  348,
      348,  348,  348,  349,  348,  349,  348,  348,  348,  348,
      348,  350,  350,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,   73,  348,  348,   83,  348,  348,  348,

      348,   73,  348,  348,  348,  348,  348,  348,  348,   73,
       83,   83,  349,  350,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,  348,  348,  343,  343,  343,  351,  351,  343,
      343,  352,  343,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
      348,  348,  348,  197,  197,  348,  348,  348,  348,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,  343,  343,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,  348,  348,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
      343,  343,   45,   45,   45,   45,   45,   45,  348,  348,
       83,   83,   83,   83,   83,   83,  343,  343,   45,   45,
      348,  348,   83,   83,  343,  343,   45,  348,  348,   83,
      343,  348,    0,  343,  343,  343,  343,  343,  343,  343,
      343,  343
    } ;

static yyconst flex_int16_t yy_nxt[928] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   33,   34,    4,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   32,   32,   44,   32,   32,   32,   45,
       46,   32,   32,   47,   48,   49,   50,   51,   32,   32,
       52,   53,   54,   55,   56,   57,    6,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   83,   83,   84,   85,   56,   86,   87,

       88,   89,   90,   91,   92,   93,   94,   83,   83,   95,
       83,   83,   83,   96,   97,   83,   83,   98,   99,  100,
      101,  102,   83,   83,  103,  104,  105,  106,  110,  112,
      115,  168,  120,  129,  113,  121,  130,  122,  122,  131,
      114,  233,  123,  124,  121,  116,  125,  125,  128,  128,
      342,  126,  127,  143,  144,  121,  111,  133,  133,  121,
      136,  133,  133,  137,  341,  139,  138,  134,  169,  193,
      193,  134,  140,  141,  145,  146,  146,  130,  234,  134,
      180,  208,  209,  134,  148,  145,  146,  146,  130,  149,
      145,  146,  146,  130,  340,  181,  135,  145,  146,  146,

      130,  145,  146,  146,  130,  145,  146,  146,  130,  145,
      146,  146,  130,  343,  109,  109,  150,  175,  117,  117,
      152,  117,  213,  339,  151,  338,  170,  214,  153,  145,
      146,  146,  130,  145,  146,  146,  130,  147,  154,  145,
      146,  146,  130,  220,  222,  176,  204,  147,  155,  183,
      147,  223,  162,  205,  206,  147,  221,  157,  159,  147,
      147,  156,  147,  336,  158,  147,  166,  163,  128,  128,
      335,  160,  147,  334,  164,  147,  161,  147,  165,  147,
      147,  147,  177,  333,  147,  332,  185,  178,  167,  186,
      331,  187,  187,  179,  147,  110,  188,  189,  186,  147,

      190,  190,  237,  224,  328,  191,  192,  194,  201,  145,
      195,  202,  130,  196,  203,  343,  225,  197,  197,  197,
      197,  226,  110,  111,  327,  118,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  186,
      111,  198,  198,  186,  282,  198,  198,  121,  283,  122,
      122,  199,  128,  128,  121,  199,  125,  125,  145,  134,
      326,  243,  134,  199,  343,  325,  134,  199,  343,  109,
      240,  134,  240,  210,  134,  241,  241,  147,  134,  170,
      200,  210,  211,  211,  195,  145,  238,  238,  130,  324,

      147,  212,  212,  212,  212,  147,  343,  117,  193,  193,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  121,  145,  133,  133,  130,  147,  323,
      343,  147,  147,  322,  244,  134,  245,  266,  147,  266,
      321,  147,  267,  267,  147,  147,  147,  134,  147,  147,
      147,  147,  147,  248,  246,  247,  147,  210,  147,  147,
      269,  147,  147,  170,  320,  147,  147,  319,  249,  250,
      147,  147,  147,  251,  147,  147,  147,  147,  147,  312,
      147,  147,  147,  272,  273,  109,  109,  147,  175,  147,

      252,  147,  147,  147,  147,  147,  147,  255,  253,  147,
      147,  147,  147,  254,  147,  311,  147,  147,  258,  210,
      310,  147,  147,  147,  147,  170,  176,  147,  309,  256,
      147,  260,  147,  257,  308,  147,  147,  259,  117,  117,
      147,  147,  186,  147,  187,  187,  263,  186,  147,  190,
      190,  193,  193,  186,  199,  198,  198,  109,  109,  199,
      175,  199,  241,  241,  307,  199,  199,  241,  241,  183,
      306,  199,  305,  199,  264,  264,  304,  199,  145,  238,
      238,  130,  303,  265,  265,  265,  265,  302,  176,  267,
      267,  301,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  268,  268,  210,  117,  117,
      145,  238,  238,  130,  268,  268,  170,  289,  147,  147,
      292,  291,  290,  268,  268,  268,  268,  268,  268,  147,
      147,  147,  147,  147,  300,  147,  147,  147,  147,  183,
      147,  147,  147,  147,  293,  294,  299,  147,  145,  147,
      147,  288,  147,  147,  147,  287,  147,  286,  147,  147,
      295,  147,  147,  147,  147,  147,  285,  147,  147,  296,
      147,  147,  147,  147,  147,  297,  284,  147,  267,  267,
      281,  147,  147,  147,  147,  147,  147,  147,  314,  147,

      147,  147,  147,  298,  147,  147,  147,  147,  280,  147,
      279,  147,  268,  268,  313,  278,  277,  276,  147,  275,
      147,  268,  268,  147,  147,  315,  147,  274,  147,  271,
      268,  268,  268,  268,  268,  268,  147,  147,  270,  147,
      316,  147,  147,  147,  147,  317,  147,  147,  210,  147,
      147,  318,  262,  147,  147,  261,  147,  147,  172,  147,
      147,  147,  171,  147,  118,  147,  147,  329,  147,  147,
      147,  147,  147,  147,  145,  147,  330,  147,  236,  147,
      147,  147,  147,  235,  343,  107,  147,  147,  232,  231,
      230,  147,  147,  147,  147,  229,  337,  147,  147,  147,

      109,  109,  109,  109,  109,  109,  109,  117,  117,  228,
      117,  117,  117,  117,  132,  227,  132,  132,  147,  147,
      219,  147,  170,  218,  170,  170,  170,  170,  170,  174,
      174,  174,  174,  174,  174,  174,  182,  182,  182,  182,
      182,  182,  182,  239,  239,  217,  239,  242,  216,  242,
      215,  207,  184,  173,  172,  171,  142,  119,  118,  108,
      107,  343,    3,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343
    } ;

static yyconst flex_int16_t yy_chk[928] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    9,   10,
       13,   53,   18,   22,   10,   18,   22,   18,   18,   22,
       10,  104,   18,   20,   20,   13,   20,   20,   21,   21,
      339,   20,   20,   29,   29,   23,    9,   23,   23,   24,
       25,   24,   24,   25,  336,   27,   25,   23,   53,   72,
       72,   24,   27,   27,   32,   32,   32,   32,  104,   23,
       64,   80,   80,   24,   33,   38,   38,   38,   38,   33,
       39,   39,   39,   39,  333,   64,   23,   33,   33,   33,

       33,   40,   40,   40,   40,   41,   41,   41,   41,   42,
       42,   42,   42,  118,   60,   60,   38,   60,   65,   65,
       40,  118,   84,  332,   39,  331,   65,   84,   41,   43,
       43,   43,   43,   44,   44,   44,   44,   46,   42,   45,
       45,   45,   45,   94,   95,   60,   78,   47,   43,   65,
       46,   95,   46,   78,   78,   46,   94,   44,   45,   48,
       47,   43,   49,  328,   44,   47,   50,   47,  121,  121,
      327,   45,   48,  325,   48,   49,   45,   48,   49,   50,
       49,   51,   61,  323,   50,  320,   69,   61,   51,   69,
      319,   69,   69,   61,   51,  109,   69,   71,   71,   51,

       71,   71,  117,   96,  312,   71,   71,   73,   76,  129,
       73,   76,  129,   73,   76,  129,   96,   73,   73,   73,
       73,   96,  148,  109,  311,  117,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   74,
      148,   74,   74,   75,  229,   75,   75,  122,  229,  122,
      122,   74,  128,  128,  125,   75,  125,  125,  137,  122,
      310,  137,  128,   74,  137,  308,  125,   75,  176,  176,
      134,  122,  134,  194,  128,  134,  134,  146,  125,  194,
       74,   83,   83,   83,   83,  132,  132,  132,  132,  306,

      146,   83,   83,   83,   83,  146,  183,  183,  186,  186,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,  133,  145,  133,  133,  145,  147,  304,
      145,  150,  151,  303,  150,  133,  151,  199,  152,  199,
      301,  147,  199,  199,  150,  151,  147,  133,  153,  150,
      151,  152,  154,  153,  152,  152,  152,  202,  156,  155,
      202,  153,  157,  202,  300,  154,  153,  299,  154,  155,
      154,  156,  155,  156,  158,  157,  156,  155,  159,  288,
      157,  160,  162,  217,  217,  174,  174,  158,  174,  163,

      159,  159,  158,  161,  160,  162,  159,  163,  160,  160,
      162,  164,  163,  161,  165,  287,  161,  163,  165,  210,
      286,  161,  166,  167,  164,  210,  174,  165,  282,  164,
      244,  167,  165,  164,  281,  166,  167,  166,  182,  182,
      166,  167,  187,  244,  187,  187,  182,  190,  244,  190,
      190,  193,  193,  198,  187,  198,  198,  213,  213,  190,
      213,  193,  240,  240,  280,  198,  187,  241,  241,  182,
      276,  190,  275,  193,  197,  197,  274,  198,  238,  238,
      238,  238,  273,  197,  197,  197,  197,  272,  213,  266,
      266,  271,  197,  197,  197,  197,  197,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  200,  200,  269,  214,  214,
      239,  239,  239,  239,  200,  200,  214,  245,  246,  247,
      248,  247,  246,  200,  200,  200,  200,  200,  200,  250,
      245,  246,  247,  248,  262,  245,  246,  247,  248,  214,
      249,  251,  250,  252,  249,  250,  261,  250,  243,  253,
      254,  236,  255,  249,  251,  235,  252,  232,  249,  251,
      254,  252,  253,  254,  257,  255,  231,  253,  254,  255,
      255,  256,  258,  259,  290,  256,  230,  257,  267,  267,
      228,  291,  257,  260,  256,  258,  259,  290,  291,  256,

      258,  259,  290,  260,  291,  289,  260,  292,  226,  291,
      225,  260,  268,  268,  289,  224,  221,  220,  289,  219,
      292,  268,  268,  289,  293,  292,  295,  218,  297,  216,
      268,  268,  268,  268,  268,  268,  294,  293,  215,  295,
      294,  297,  293,  296,  295,  296,  297,  298,  195,  294,
      313,  298,  179,  314,  294,  178,  296,  315,  172,  316,
      298,  296,  171,  313,  149,  298,  314,  315,  313,  317,
      315,  314,  316,  318,  130,  315,  317,  316,  114,  329,
      330,  337,  317,  113,  111,  107,  318,  317,  102,  101,
      100,  318,  329,  330,  337,   99,  329,  329,  330,  337,

      344,  344,  344,  344,  344,  344,  344,  345,  345,   98,
      345,  345,  345,  345,  346,   97,  346,  346,  347,  347,
       93,  347,  348,   92,  348,  348,  348,  348,  348,  349,
      349,  349,  349,  349,  349,  349,  350,  350,  350,  350,
      350,  350,  350,  351,  351,   91,  351,  352,   90,  352,
       89,   79,   68,   59,   58,   57,   28,   17,   14,    8,
        5,    3,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/ast.l"
#line 2 "src/ast.l"

#include "corto/ast/_type.h"
#include "ast__private.h"
#include "y.tab.h"
#define MAX_DEPTH (72)

static void comment(void);
ast_Parser yparser(void);

int nesting = 0; /* Ignore indents & newlines between {}, (), [] */
int trailing = 0; /* Ignore indents & newlines after a binary operator */
int block = 0; /* Ignore newline directly after an open scope/block */
unsigned int indent_stack[MAX_DEPTH];
unsigned int level = 0;

static int process_indent(char* line);

#define NEWLINE \
    yparser()->line++;\
    yparser()->column = 0;\

#define TOKEN\
    yparser()->column += strlen(yytext);\
    yparser()->token = yytext;\
    trailing = fast_trailingOperator();\
    block = fast_blockOperator();

void lex_collect(void *o) {
    ast_Parser_collectHeap(yparser(), (corto_word)o);
}

/* The following operators can be trailing */
static char *operators[] = {
    "=", "+", "-", "*", "/", "%", "&", "|", "^",
    "==", "!=", ">", "<", ">=", "<=", "||", "&&", ","};
static int fast_trailingOperator(void) {
    int length = sizeof(operators) / sizeof(char*);
    int i;
    if (yparser()->token) {
        for(i = 0; i < length; i++) {
            if (!strcmp(operators[i], yparser()->token)) {
                return TRUE;
            }
        }
    }
    return FALSE;
}

static int fast_blockOperator(void) {
    if (yparser()->token) {
        if (!strcmp(yparser()->token, ":") ||
            !strcmp(yparser()->token, "::") ||
            !strcmp(yparser()->token, ":/") ||
            !strcmp(yparser()->token, ":::")) {
            return TRUE;
        }
    }
    return FALSE;
}

static int fast_isBlankLine(char *txt, int *isComment) {
    char *ptr = txt, ch;
    while ((ch = *ptr)) {
        if (ch == '/') {
            if (ptr[1] == '/') {
                *isComment = TRUE;
            }
        }
        if ((ch != ' ') && (ch != '\t') && (ch != '\n') && (ch != 13)) {
            return FALSE;
        }
        ptr++;
    }
    return TRUE;
}

/* Escape character */
static char *fast_charesc(char *in, corto_char *out) {
    switch(*in) {
    case '\\':
        in++;
        switch(*in) {
        case 'a':
            *out = '\a';
            break;
        case 'b':
            *out = '\b';
            break;
        case 'f':
            *out = '\f';
            break;
        case 'n':
            *out = '\n';
            break;
        case 'r':
            *out = '\r';
            break;
        case 't':
            *out = '\t';
            break;
        case 'v':
            *out = '\v';
            break;
        case '\'':
            *out = '\'';
            break;
        case '0':
            *out = '\0';
            break;
        case '"':
            *out = '"';
            break;
        case '\\':
            *out = '\\';
            break;
        case '?':
            *out = '?';
            break;
        default:
            ast_Parser_error(yparser(), "invalid escape sequence '%c'",  *in);
            goto error;
            break;
        }
        break;
    default:
        *out = *in;
        break;
    }

    return in + 1;
error:
    return NULL;
}

/* Escape string-token */
static int fast_stresc(char* yptr, corto_string ptr) {
    char ch;

    /* Do escape sequences */
    yptr = yytext+1;
    while((ch = *yptr) && (ch != '"')) {
        yptr = fast_charesc(yptr, ptr);
        if(!yptr) {
            goto error;
        }
        ptr++;
    }
    *ptr = '\0';

    return 0;
error:
    return -1;
}

static void fast_doIndents(int indent);

#line 938 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 163 "src/ast.l"


#line 1158 "src/lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 344 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 863 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 165 "src/ast.l"
{
                                    /* Filter out empty lines */
                                    int isComment = FALSE;
                                    if (!fast_isBlankLine(yytext, &isComment)) {
                                        int last = yyleng - 1;
                                        int indent = isComment ? 0 : process_indent(yytext);
                                        while ((last >= 0) && (yytext[last] != ' ')) {
                                            unput(yytext[last]);
                                            last--;
                                        }
                                        fast_doIndents(indent);
                                    }
                                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 179 "src/ast.l"
{
                                    int indent = process_indent("");
                                    if (indent) {
                                        fast_doIndents(indent);
                                    } else {
                                        return EOF;
                                    }
                                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 188 "src/ast.l"
TOKEN; return SCOPEPRE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 189 "src/ast.l"
TOKEN; return SCOPE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 190 "src/ast.l"
TOKEN; return SCOPE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 191 "src/ast.l"
TOKEN; return ':';
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 193 "src/ast.l"
TOKEN; return KW_IF;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 194 "src/ast.l"
TOKEN; return KW_ELSE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 195 "src/ast.l"
TOKEN; return KW_WHILE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 196 "src/ast.l"
TOKEN; return KW_SWITCH;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 197 "src/ast.l"
TOKEN; return KW_CASE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 198 "src/ast.l"
TOKEN; return KW_DEFAULT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 199 "src/ast.l"
TOKEN; return KW_BREAK;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 200 "src/ast.l"
TOKEN; return KW_FOR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 201 "src/ast.l"
TOKEN; return KW_TRY;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 202 "src/ast.l"
TOKEN; return KW_CATCH;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 203 "src/ast.l"
TOKEN; return KW_LOCAL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 204 "src/ast.l"
TOKEN; return LAND;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 205 "src/ast.l"
TOKEN; return LOR;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 206 "src/ast.l"
TOKEN; return LNOT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "src/ast.l"
TOKEN; return KW_IN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 208 "src/ast.l"
TOKEN; return IMPORT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 210 "src/ast.l"
TOKEN; yylval.Boolean =  TRUE; return BOOLEAN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 211 "src/ast.l"
TOKEN; yylval.Boolean = FALSE; return BOOLEAN;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 212 "src/ast.l"
TOKEN; yylval.FloatingPoint = NAN; return FLOATINGPOINT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 214 "src/ast.l"
TOKEN; return PACKAGE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 215 "src/ast.l"
TOKEN; return IMPORT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 216 "src/ast.l"
comment();
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 217 "src/ast.l"
comment();
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 219 "src/ast.l"
TOKEN; return INDENT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 220 "src/ast.l"
TOKEN; return DEDENT;
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 222 "src/ast.l"
TOKEN; fast_charesc(yytext+1, &yylval.Character); return CHARACTER;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 223 "src/ast.l"
TOKEN; sscanf(yytext, "%" PRIx64, &yylval.Integer); return INTEGER;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 224 "src/ast.l"
TOKEN; sscanf(yytext, "%" PRIi64, &yylval.SignedInteger); return SIGNEDINTEGER;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 225 "src/ast.l"
TOKEN; sscanf(yytext, "%" PRIu64, &yylval.Integer); return INTEGER;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 226 "src/ast.l"
TOKEN; yylval.FloatingPoint = atof(yytext); return FLOATINGPOINT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 227 "src/ast.l"
TOKEN; yylval.Null = NULL; return NUL;
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 228 "src/ast.l"
TOKEN; yylval.String = malloc(strlen(yytext) + 1); lex_collect(yylval.String); return fast_stresc(yytext+1,yylval.String) ? ERROR : STRING;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 229 "src/ast.l"
TOKEN; return TAB;
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 230 "src/ast.l"
NEWLINE; if (!nesting && !trailing && !block) { return ENDL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 231 "src/ast.l"
NEWLINE; return ENDL;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 232 "src/ast.l"
TOKEN; nesting++; return '(';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 233 "src/ast.l"
TOKEN; nesting--; return ')';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 234 "src/ast.l"
TOKEN; nesting++; return '[';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 235 "src/ast.l"
TOKEN; nesting--; return ']';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 236 "src/ast.l"
TOKEN; nesting++; return '{';
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 237 "src/ast.l"
TOKEN; nesting--; return '}';
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 238 "src/ast.l"
TOKEN; return '.';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 239 "src/ast.l"
TOKEN; return ',';
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 240 "src/ast.l"
TOKEN; return '+';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 241 "src/ast.l"
TOKEN; return '-';
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 242 "src/ast.l"
TOKEN; return '*';
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 243 "src/ast.l"
TOKEN; return '/';
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 244 "src/ast.l"
TOKEN; return '%';
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 245 "src/ast.l"
TOKEN; return INC;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "src/ast.l"
TOKEN; return DEC;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 247 "src/ast.l"
TOKEN; return '!';
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "src/ast.l"
TOKEN; return '&';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "src/ast.l"
TOKEN; return '~';
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "src/ast.l"
TOKEN; return '<';
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 251 "src/ast.l"
TOKEN; return '>';
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 252 "src/ast.l"
TOKEN; return '?';
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 253 "src/ast.l"
TOKEN; return LEQ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "src/ast.l"
TOKEN; return GEQ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 255 "src/ast.l"
TOKEN; return EQ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 256 "src/ast.l"
TOKEN; return NEQ;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 257 "src/ast.l"
TOKEN; return '|';
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 258 "src/ast.l"
TOKEN; return '^';
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 259 "src/ast.l"
TOKEN; return LOR;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 260 "src/ast.l"
TOKEN; return LAND;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 261 "src/ast.l"
TOKEN; return '=';
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 262 "src/ast.l"
TOKEN; return MUL_ASSIGN;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 263 "src/ast.l"
TOKEN; return DIV_ASSIGN;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 264 "src/ast.l"
TOKEN; return ADD_ASSIGN;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 265 "src/ast.l"
TOKEN; return SUB_ASSIGN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 266 "src/ast.l"
TOKEN; return OR_ASSIGN;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 267 "src/ast.l"
TOKEN; return AND_ASSIGN;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 268 "src/ast.l"
TOKEN; return UPDATE_ASSIGN;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 269 "src/ast.l"
TOKEN; return ARROW_RIGHT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 270 "src/ast.l"
TOKEN; return ARROW_LEFT;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 271 "src/ast.l"
TOKEN; return SHIFT_LEFT;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 272 "src/ast.l"
TOKEN; return SHIFT_RIGHT;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 273 "src/ast.l"
TOKEN; return '@';
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 274 "src/ast.l"
TOKEN; return '`';
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 275 "src/ast.l"
TOKEN; return '$';
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 276 "src/ast.l"
TOKEN; return '\'';
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 277 "src/ast.l"
TOKEN; yylval.Identifier = strdup(yytext); lex_collect(yylval.Identifier); return ID;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 278 "src/ast.l"
TOKEN; yylval.Identifier = strdup(yytext); lex_collect(yylval.Identifier); return GID;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 279 "src/ast.l"
yparser()->column += 1;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 282 "src/ast.l"
ECHO;
	YY_BREAK
#line 1687 "src/lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 344 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 344 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 343);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 281 "src/ast.l"



int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

/* Comment */
static void comment(void)
{
    char c;
    ast_Parser p = yparser();

    while ((c = input()) && (c != EOF) && (c != '\n')) {
    }

    if (c == EOF) {
        void ast_Parser_error(ast_Parser p, corto_string fmt, ...);
        ast_Parser_error(p, "end of file encountered in comment");
        exit(1);
    } else {
        unput('\n');
    }
}

static unsigned int white_count(char* line) {
    unsigned int count = 0;
    while (*line == ' ') {
        count++;
        line++;
    }
    return count;
}

static int process_indent(char* line) {
    int result = 0;

    if (nesting || trailing) {
        /* Ignore indents while nested. */
        return 0;
    }

    unsigned int indent = white_count(line);

    if (indent == indent_stack[level]) {
        return 0;
    }

    if (indent > indent_stack[level]) {
        indent_stack[++level] = indent;
        return 1;
    }

    while (indent < indent_stack[level]) {
        result--;
        --level;
    }

    return result;
}

static void fast_doIndents(int indent) {
    if (indent > 0) {
        unput(' ');
        unput('i');
        unput('#');
    } else if (indent) {
        while (indent) {
            unput(' ');
            unput('d');
            unput('#');
            indent++;
        }
    }
}

