#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[330] =
    {   0,
        0,    0,   89,   88,   37,   38,   87,   55,   88,   27,
       83,   52,   56,   84,   40,   41,   50,   48,   47,   49,
       46,   51,   33,   33,    5,   39,   58,   69,   59,   60,
       81,   85,   85,   42,   43,   66,   82,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       44,   65,   45,   57,    1,    1,   87,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,   37,   64,    0,   36,    0,   29,
       28,    0,   68,   75,    0,    0,   70,   53,    0,   34,
       72,   54,   32,   73,   77,   34,   26,    0,   71,   86,
       33,    0,    0,    3,    4,   76,   78,   79,   61,   63,
       62,   80,    0,   85,   85,    0,    0,   85,   85,   85,
       85,   85,   85,    6,   19,   85,   85,   85,   17,   85,
       85,   85,   85,   85,   74,   67,    1,    1,    0,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        0,    0,   30,   86,   86,    0,   34,   31,    2,   16,
       85,   85,   85,   85,   85,   12,   23,   18,   85,   85,
       85,   13,   20,   15,   85,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        0,    0,   85,   10,   85,    7,   85,   35,   85,   21,
       85,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    0,    0,   11,   14,   22,   85,    8,    1,
        1,    1,    1,    1,    1,    1,    0,    0,    9,    1,
        1,    1,   25,    0,    1,    1,   24,    1,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   30,   29,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       33,   34,   35,   36,   31,   37,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   31,   47,   48,   49,   50,
       51,   52,   31,   53,   54,   55,   56,   57,   58,   59,
       60,   31,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    4,    5,
        5,    4,    1,    1,    6,    1,    1,    1,    7,    7,
        4,    4,    1,    1,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[339] =
    {   0,
        0,   64,  830,  831,  827,  831,  831,  803,  123,   89,
      831,  831,  121,  793,  831,  831,  801,  118,  831,  127,
      129,  115,  138,  142,  142,  831,  149,  800,  129,  831,
      831,  156,  179,  831,  831,  831,  831,  167,  172,  183,
      187,  191,  211,  217,  190,  189,  206,  213,  214,  215,
      831,  107,  831,  831,    0,  822,  819,  796,  216,  231,
        0,    0,  171,  245,    0,    0,  793,  260,    0,  269,
      150,  277,  320,  324,  278,    0,  199,  771,  157,    0,
        0,  361,  252,    0,    0,    0,    0,  743,  735,  744,
      723,  250,  241,  254,  717,  710,  713,  711,  725,  717,

        0,  117,    0,    0,  757,  831,  270,  831,  754,  831,
      699,  707,  831,  831,  184,  223,  831,  831,  194,  328,
      831,  831,  335,  831,  831,  331,  338,  717,  831,  292,
      354,  407,    0,  831,  404,  831,  831,  831,  831,  831,
      831,  831,  411,  338,  387,  333,  702,  393,  397,  403,
      409,  394,  413,  417,  423,  432,  429,  438,  439,  453,
      454,  455,  462,  470,  831,  831,    0,  723,  706,    0,
      516,    0,  365,    0,  657,  667,    0,    0,  520,  382,
        0,    0,  367,  507,    0,    0,  514,    0,    0,  509,
      421,  678,    0,  537,  522,  481,  578,    0,  453,    0,

        0,    0,    0,    0,    0,    0,  437,    0,    0,  567,
      599,  658,  656,  343,  643,  643,  637,    0,    0,  636,
      625,  630,    0,  631,  287,  632,  608,  600,    0,    0,
      592,  595,  831,  526,  540,  584,  591,    0,  607,  571,
      575,  586,  585,  592,  600,  594,  601,  602,  611,  609,
      628,  617,  625,  631,  637,  554,  560,    0,    0,    0,
      594,  651,  674,  552,    0,  534,  523,  523,  513,  499,
        0,    0,    0,  493,  483,  494,    0,    0,    0,  485,
      466,  465,  645,  651,  673,  670,  681,  671,  690,  682,
      693,  456,  456,  440,    0,  436,    0,  429,    0,  412,

        0,  395,  342,  340,  696,  702,  704,  705,  713,  318,
      326,    0,    0,    0,  314,    0,  243,  249,  716,  227,
      230,    0,  831,  123,    0,  109,  831,    0,  831,  772,
      779,  783,  787,  794,  801,  808,  812,  815
    } ;

static yyconst flex_int16_t yy_def[339] =
    {   0,
      329,  329,  329,  329,  329,  329,  329,  329,  330,  329,
      329,  329,  329,  331,  329,  329,  329,  329,  329,  329,
      329,  332,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  333,  333,  329,  329,  329,  329,  333,  333,  333,
      333,  333,  333,  333,   44,   44,   44,   44,   44,   44,
      329,  329,  329,  329,  334,  334,  334,  334,  335,  334,
      334,  334,  334,  336,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,   82,  334,  334,  334,  334,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

      334,  334,  334,  334,  329,  329,  330,  329,  330,  329,
      329,  329,  329,  329,  331,  331,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  332,  329,  329,  337,
      329,  329,  338,  329,  332,  329,  329,  329,  329,  329,
      329,  329,  332,   44,   44,  330,  331,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,  329,  329,  334,  334,  334,  334,
      335,  334,  335,  334,  334,  334,  334,  334,  336,  336,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
       72,  334,  334,   82,  334,  334,  334,  334,   72,  334,

      334,  334,  334,  334,  334,  334,   72,   82,   82,  335,
      336,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,  334,  334,
      329,  329,  329,  337,  337,  329,  329,  338,  329,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,  334,  334,  334,  194,  194,
      334,  334,  334,  334,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
      329,  329,   44,   44,   44,   44,   44,   44,   44,   44,
       44,  334,  334,   82,   82,   82,   82,   82,   82,   82,

       82,   82,  329,  329,   44,   44,   44,   44,   44,  334,
      334,   82,   82,   82,   82,   82,  329,  329,   44,  334,
      334,   82,  329,  329,  334,  334,  329,  334,    0,  329,
      329,  329,  329,  329,  329,  329,  329,  329
    } ;

static yyconst flex_uint16_t yy_nxt[896] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   33,   34,    4,   35,   36,   37,   38,   39,   40,
       32,   41,   42,   32,   32,   43,   32,   32,   32,   44,
       45,   32,   32,   46,   47,   48,   49,   50,   32,   32,
       51,   52,   53,   54,   55,   56,    6,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   82,   82,   83,   84,   55,   85,   86,

       87,   88,   89,   90,   82,   91,   92,   82,   82,   93,
       82,   82,   82,   94,   95,   82,   82,   96,   97,   98,
       99,  100,   82,   82,  101,  102,  103,  104,  108,  110,
      113,  165,  118,  127,  111,  119,  128,  120,  120,  129,
      112,  229,  121,  122,  119,  114,  123,  123,  126,  126,
      328,  124,  125,  141,  142,  119,  109,  131,  131,  119,
      134,  131,  131,  135,  327,  137,  136,  132,  166,  190,
      190,  132,  138,  139,  143,  144,  144,  128,  230,  132,
      177,  205,  206,  132,  146,  143,  144,  144,  128,  147,
      143,  144,  144,  128,  233,  178,  133,  143,  144,  144,

      128,  143,  144,  144,  128,  143,  144,  144,  128,  143,
      144,  144,  128,  126,  126,  201,  148,  116,  107,  107,
      150,  172,  202,  203,  149,  329,  145,  145,  152,  143,
      144,  144,  128,  115,  151,  143,  144,  144,  128,  145,
      145,  153,  159,  145,  145,  145,  160,  115,  115,  173,
      145,  163,  145,  154,  156,  167,  145,  210,  161,  164,
      155,  145,  211,  145,  145,  145,  162,  157,  145,  145,
      145,  174,  158,  326,  182,  108,  175,  183,  180,  184,
      184,  325,  176,  218,  185,  186,  183,  216,  187,  187,
      219,  220,  324,  188,  189,  191,  198,  323,  192,  199,

      217,  193,  200,  109,  221,  194,  194,  194,  194,  222,
      143,  234,  234,  128,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  183,  108,  195,
      195,  183,  276,  195,  195,  119,  277,  120,  120,  196,
      126,  126,  119,  196,  123,  123,  143,  132,  322,  128,
      132,  196,  329,  321,  132,  196,  109,  329,  107,  132,
      320,  119,  132,  131,  131,  145,  132,  318,  197,  207,
      208,  208,  192,  132,  329,  115,  190,  190,  145,  209,
      209,  209,  209,  145,  317,  132,  267,  268,  209,  209,

      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  236,  143,  236,  145,  239,  237,  237,  329,  143,
      145,  145,  128,  240,  145,  329,  316,  145,  241,  207,
      145,  245,  145,  145,  145,  167,  145,  145,  145,  145,
      145,  315,  145,  145,  145,  207,  242,  243,  145,  145,
      145,  167,  244,  145,  145,  246,  145,  145,  145,  145,
      314,  207,  145,  145,  264,  145,  145,  167,  145,  145,
      313,  247,  145,  248,  145,  249,  312,  145,  145,  145,
      145,  145,  145,  145,  145,  261,  253,  261,  250,  145,

      262,  262,  311,  145,  145,  145,  310,  145,  145,  251,
      145,  304,  145,  252,  254,  255,  303,  145,  107,  107,
      145,  172,  115,  115,  183,  145,  184,  184,  190,  190,
      258,  183,  302,  187,  187,  301,  196,  300,  196,  183,
      299,  195,  195,  196,  143,  234,  234,  128,  196,  173,
      196,  196,  298,  180,  297,  196,  259,  259,  143,  234,
      234,  128,  296,  196,  295,  260,  260,  260,  260,  107,
      107,  294,  172,  207,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  263,  263,  293,

      173,  115,  115,  237,  237,  292,  263,  263,  145,  167,
      237,  237,  283,  262,  262,  263,  263,  263,  263,  263,
      263,  145,  145,  145,  285,  145,  145,  284,  143,  145,
      145,  145,  180,  286,  282,  145,  145,  145,  145,  145,
      145,  145,  145,  281,  145,  280,  145,  145,  145,  145,
      145,  145,  145,  287,  145,  145,  145,  145,  288,  145,
      279,  145,  145,  289,  145,  145,  145,  145,  145,  290,
      262,  262,  145,  278,  145,  145,  275,  274,  145,  273,
      145,  145,  145,  145,  291,  272,  145,  145,  145,  271,
      270,  305,  145,  263,  263,  145,  269,  266,  265,  207,

      145,  145,  263,  263,  257,  256,  145,  145,  145,  169,
      145,  263,  263,  263,  263,  263,  263,  306,  145,  145,
      145,  145,  307,  145,  168,  145,  145,  145,  145,  308,
      145,  145,  145,  145,  309,  116,  145,  145,  143,  145,
      145,  145,  145,  145,  232,  145,  145,  231,  145,  319,
      145,  145,  145,  145,  145,  145,  329,  145,  105,  145,
      145,  228,  227,  145,  226,  225,  145,  224,  145,  223,
      215,  145,  107,  107,  107,  107,  107,  107,  107,  115,
      115,  214,  115,  115,  115,  115,  130,  213,  130,  130,
      145,  145,  212,  145,  167,  204,  167,  167,  167,  167,

      167,  171,  171,  171,  171,  171,  171,  171,  179,  179,
      179,  179,  179,  179,  179,  235,  235,  181,  235,  238,
      170,  238,  169,  168,  140,  117,  116,  106,  105,  329,
        3,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329

    } ;

static yyconst flex_int16_t yy_chk[896] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    9,   10,
       13,   52,   18,   22,   10,   18,   22,   18,   18,   22,
       10,  102,   18,   20,   20,   13,   20,   20,   21,   21,
      326,   20,   20,   29,   29,   23,    9,   23,   23,   24,
       25,   24,   24,   25,  324,   27,   25,   23,   52,   71,
       71,   24,   27,   27,   32,   32,   32,   32,  102,   23,
       63,   79,   79,   24,   33,   38,   38,   38,   38,   33,
       39,   39,   39,   39,  115,   63,   23,   33,   33,   33,

       33,   40,   40,   40,   40,   41,   41,   41,   41,   42,
       42,   42,   42,  119,  119,   77,   38,  115,   59,   59,
       40,   59,   77,   77,   39,  116,   46,   45,   42,   43,
       43,   43,   43,  116,   41,   44,   44,   44,   44,   46,
       45,   42,   45,   47,   46,   45,   46,   64,   64,   59,
       48,   49,   50,   43,   44,   64,   47,   83,   47,   50,
       43,   47,   83,   48,   49,   50,   48,   44,   48,   49,
       50,   60,   44,  321,   68,  107,   60,   68,   64,   68,
       68,  320,   60,   93,   68,   70,   70,   92,   70,   70,
       93,   94,  318,   70,   70,   72,   75,  317,   72,   75,

       92,   72,   75,  107,   94,   72,   72,   72,   72,   94,
      130,  130,  130,  130,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   73,  146,   73,
       73,   74,  225,   74,   74,  120,  225,  120,  120,   73,
      126,  126,  123,   74,  123,  123,  127,  120,  315,  127,
      126,   73,  127,  311,  123,   74,  146,  173,  173,  120,
      310,  131,  126,  131,  131,  144,  123,  304,   73,   82,
       82,   82,   82,  131,  180,  180,  183,  183,  144,   82,
       82,   82,   82,  144,  303,  131,  214,  214,   82,   82,

       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,  132,  135,  132,  145,  135,  132,  132,  135,  143,
      148,  152,  143,  148,  149,  143,  302,  145,  149,  191,
      150,  152,  145,  148,  152,  191,  151,  149,  148,  152,
      153,  300,  149,  150,  154,  207,  150,  150,  150,  151,
      155,  207,  151,  153,  151,  153,  157,  154,  153,  156,
      298,  199,  154,  155,  199,  158,  159,  199,  155,  157,
      296,  156,  156,  157,  157,  158,  294,  156,  158,  159,
      160,  161,  162,  158,  159,  196,  162,  196,  160,  163,

      196,  196,  293,  160,  161,  162,  292,  164,  160,  161,
      162,  282,  163,  161,  163,  164,  281,  163,  171,  171,
      164,  171,  179,  179,  184,  164,  184,  184,  190,  190,
      179,  187,  280,  187,  187,  276,  184,  275,  190,  195,
      274,  195,  195,  187,  234,  234,  234,  234,  184,  171,
      190,  195,  270,  179,  269,  187,  194,  194,  235,  235,
      235,  235,  268,  195,  267,  194,  194,  194,  194,  210,
      210,  266,  210,  264,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  197,  197,  257,

      210,  211,  211,  236,  236,  256,  197,  197,  240,  211,
      237,  237,  241,  261,  261,  197,  197,  197,  197,  197,
      197,  240,  243,  242,  243,  241,  240,  242,  239,  244,
      241,  246,  211,  244,  232,  243,  242,  245,  247,  248,
      243,  242,  244,  231,  246,  228,  250,  244,  249,  246,
      245,  247,  248,  245,  252,  245,  247,  248,  249,  250,
      227,  249,  253,  250,  250,  251,  249,  252,  254,  251,
      262,  262,  252,  226,  255,  253,  224,  222,  251,  221,
      253,  254,  283,  251,  255,  220,  254,  255,  284,  217,
      216,  283,  255,  263,  263,  283,  215,  213,  212,  192,

      283,  284,  263,  263,  176,  175,  284,  286,  288,  169,
      285,  263,  263,  263,  263,  263,  263,  285,  287,  290,
      286,  288,  287,  285,  168,  286,  288,  289,  285,  289,
      291,  287,  290,  305,  291,  147,  287,  290,  128,  306,
      289,  307,  308,  291,  112,  289,  305,  111,  291,  308,
      309,  305,  306,  319,  307,  308,  109,  306,  105,  307,
      308,  100,   99,  309,   98,   97,  319,   96,  309,   95,
       91,  319,  330,  330,  330,  330,  330,  330,  330,  331,
      331,   90,  331,  331,  331,  331,  332,   89,  332,  332,
      333,  333,   88,  333,  334,   78,  334,  334,  334,  334,

      334,  335,  335,  335,  335,  335,  335,  335,  336,  336,
      336,  336,  336,  336,  336,  337,  337,   67,  337,  338,
       58,  338,   57,   56,   28,   17,   14,    8,    5,    3,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ast.l"
#line 2 "ast.l"

#include "corto/ast/_type.h"
#include "ast__private.h"
#include "y.tab.h"
#define MAX_DEPTH (72)

static void comment(void);
ast_Parser yparser(void);

int nesting = 0; /* Ignore indents & newlines between {}, (), [] */
int trailing = 0; /* Ignore indents & newlines after a binary operator */
int block = 0; /* Ignore newline directly after an open scope/block */
unsigned int indent_stack[MAX_DEPTH];
unsigned int level = 0;

static int process_indent(char* line);

#define NEWLINE \
    yparser()->line++;\
    yparser()->column = 0;\

#define TOKEN\
    yparser()->column += strlen(yytext);\
    yparser()->token = yytext;\
    trailing = fast_trailingOperator();\
    block = fast_blockOperator();

void lex_collect(void *o) {
    ast_Parser_collectHeap(yparser(), (corto_word)o);
}

/* The following operators can be trailing */
static char *operators[] = {
    "=", "+", "-", "*", "/", "%", "&", "|", "^",
    "==", "!=", ">", "<", ">=", "<=", "||", "&&", ","};
static int fast_trailingOperator(void) {
    int length = sizeof(operators) / sizeof(char*);
    int i;
    if (yparser()->token) {
        for(i = 0; i < length; i++) {
            if (!strcmp(operators[i], yparser()->token)) {
                return TRUE;
            }
        }
    }
    return FALSE;
}

static int fast_blockOperator(void) {
    if (yparser()->token) {
        if (!strcmp(yparser()->token, ":") ||
            !strcmp(yparser()->token, "::") ||
            !strcmp(yparser()->token, ":/") ||
            !strcmp(yparser()->token, ":::")) {
            return TRUE;
        }
    }
    return FALSE;
}

static int fast_isBlankLine(char *txt, int *isComment) {
    char *ptr = txt, ch;
    while ((ch = *ptr)) {
        if (ch == '/') {
            if (ptr[1] == '/') {
                *isComment = TRUE;
            }
        }
        if ((ch != ' ') && (ch != '\t') && (ch != '\n') && (ch != 13)) {
            return FALSE;
        }
        ptr++;
    }
    return TRUE;
}

/* Escape character */
static char *fast_charesc(char *in, corto_char *out) {
    switch(*in) {
    case '\\':
        in++;
        switch(*in) {
        case 'a':
            *out = '\a';
            break;
        case 'b':
            *out = '\b';
            break;
        case 'f':
            *out = '\f';
            break;
        case 'n':
            *out = '\n';
            break;
        case 'r':
            *out = '\r';
            break;
        case 't':
            *out = '\t';
            break;
        case 'v':
            *out = '\v';
            break;
        case '\'':
            *out = '\'';
            break;
        case '0':
            *out = '\0';
            break;
        case '"':
            *out = '"';
            break;
        case '\\':
            *out = '\\';
            break;
        case '?':
            *out = '?';
            break;
        default:
            ast_Parser_error(yparser(), "invalid escape sequence '%c'",  *in);
            goto error;
            break;
        }
        break;
    default:
        *out = *in;
        break;
    }

    return in + 1;
error:
    return NULL;
}

/* Escape string-token */
static int fast_stresc(char* yptr, corto_string ptr) {
    char ch;

    /* Do escape sequences */
    yptr = yytext+1;
    while((ch = *yptr) && (ch != '"')) {
        yptr = fast_charesc(yptr, ptr);
        if(!yptr) {
            goto error;
        }
        ptr++;
    }
    *ptr = '\0';

    return 0;
error:
    return -1;
}

static void fast_doIndents(int indent);

#line 932 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 163 "ast.l"


#line 1156 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 330 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 831 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 165 "ast.l"
{
                                    /* Filter out empty lines */
                                    int isComment = FALSE;
                                    if (!fast_isBlankLine(yytext, &isComment)) {
                                        int last = yyleng - 1;
                                        int indent = isComment ? 0 : process_indent(yytext);
                                        while ((last >= 0) && (yytext[last] != ' ')) {
                                            unput(yytext[last]);
                                            last--;
                                        }
                                        fast_doIndents(indent);
                                    }
                                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 179 "ast.l"
{
                                    int indent = process_indent("");
                                    if (indent) {
                                        fast_doIndents(indent);
                                    } else {
                                        return EOF;
                                    }
                                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 188 "ast.l"
TOKEN; return SCOPEPRE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 189 "ast.l"
TOKEN; return SCOPE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 190 "ast.l"
TOKEN; return SCOPE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 191 "ast.l"
TOKEN; return ':';
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 193 "ast.l"
TOKEN; return KW_IF;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 194 "ast.l"
TOKEN; return KW_ELSE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 195 "ast.l"
TOKEN; return KW_WHILE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 196 "ast.l"
TOKEN; return KW_SWITCH;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 197 "ast.l"
TOKEN; return KW_CASE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 198 "ast.l"
TOKEN; return KW_BREAK;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 199 "ast.l"
TOKEN; return KW_FOR;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 200 "ast.l"
TOKEN; return KW_TRY;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 201 "ast.l"
TOKEN; return KW_CATCH;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 202 "ast.l"
TOKEN; return KW_LOCAL;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 203 "ast.l"
TOKEN; return LAND;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 204 "ast.l"
TOKEN; return LOR;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 205 "ast.l"
TOKEN; return LNOT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 206 "ast.l"
TOKEN; return KW_IN;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "ast.l"
TOKEN; return IMPORT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 209 "ast.l"
TOKEN; yylval.Boolean =  TRUE; return BOOLEAN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 210 "ast.l"
TOKEN; yylval.Boolean = FALSE; return BOOLEAN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 211 "ast.l"
TOKEN; yylval.FloatingPoint = NAN; return FLOATINGPOINT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 213 "ast.l"
TOKEN; return PACKAGE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 214 "ast.l"
TOKEN; return IMPORT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 215 "ast.l"
comment();
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 216 "ast.l"
comment();
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 218 "ast.l"
TOKEN; return INDENT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 219 "ast.l"
TOKEN; return DEDENT;
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 221 "ast.l"
TOKEN; fast_charesc(yytext+1, &yylval.Character); return CHARACTER;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 222 "ast.l"
TOKEN; sscanf(yytext, "%" PRIx64, &yylval.Integer); return INTEGER;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 223 "ast.l"
TOKEN; sscanf(yytext, "%" PRIi64, &yylval.SignedInteger); return SIGNEDINTEGER;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 224 "ast.l"
TOKEN; sscanf(yytext, "%" PRIu64, &yylval.Integer); return INTEGER;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 225 "ast.l"
TOKEN; yylval.FloatingPoint = atof(yytext); return FLOATINGPOINT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 226 "ast.l"
TOKEN; yylval.Null = NULL; return NUL;
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 227 "ast.l"
TOKEN; yylval.String = malloc(strlen(yytext) + 1); lex_collect(yylval.String); return fast_stresc(yytext+1,yylval.String) ? ERROR : STRING;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 228 "ast.l"
TOKEN; return TAB;
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 229 "ast.l"
NEWLINE; if (!nesting && !trailing && !block) { return ENDL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 230 "ast.l"
NEWLINE; return ENDL;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 231 "ast.l"
TOKEN; nesting++; return '(';
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 232 "ast.l"
TOKEN; nesting--; return ')';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 233 "ast.l"
TOKEN; nesting++; return '[';
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 234 "ast.l"
TOKEN; nesting--; return ']';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 235 "ast.l"
TOKEN; nesting++; return '{';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 236 "ast.l"
TOKEN; nesting--; return '}';
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 237 "ast.l"
TOKEN; return '.';
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 238 "ast.l"
TOKEN; return ',';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 239 "ast.l"
TOKEN; return '+';
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 240 "ast.l"
TOKEN; return '-';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 241 "ast.l"
TOKEN; return '*';
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 242 "ast.l"
TOKEN; return '/';
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 243 "ast.l"
TOKEN; return '%';
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 244 "ast.l"
TOKEN; return INC;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 245 "ast.l"
TOKEN; return DEC;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "ast.l"
TOKEN; return '!';
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 247 "ast.l"
TOKEN; return '&';
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "ast.l"
TOKEN; return '~';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "ast.l"
TOKEN; return '<';
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "ast.l"
TOKEN; return '>';
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 251 "ast.l"
TOKEN; return '?';
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 252 "ast.l"
TOKEN; return LEQ;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 253 "ast.l"
TOKEN; return GEQ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "ast.l"
TOKEN; return EQ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 255 "ast.l"
TOKEN; return NEQ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 256 "ast.l"
TOKEN; return '|';
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 257 "ast.l"
TOKEN; return '^';
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 258 "ast.l"
TOKEN; return LOR;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 259 "ast.l"
TOKEN; return LAND;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 260 "ast.l"
TOKEN; return '=';
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 261 "ast.l"
TOKEN; return MUL_ASSIGN;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 262 "ast.l"
TOKEN; return DIV_ASSIGN;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 263 "ast.l"
TOKEN; return ADD_ASSIGN;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 264 "ast.l"
TOKEN; return SUB_ASSIGN;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 265 "ast.l"
TOKEN; return OR_ASSIGN;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 266 "ast.l"
TOKEN; return AND_ASSIGN;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 267 "ast.l"
TOKEN; return UPDATE_ASSIGN;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 268 "ast.l"
TOKEN; return ARROW_RIGHT;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 269 "ast.l"
TOKEN; return ARROW_LEFT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 270 "ast.l"
TOKEN; return SHIFT_LEFT;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 271 "ast.l"
TOKEN; return SHIFT_RIGHT;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 272 "ast.l"
TOKEN; return '@';
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 273 "ast.l"
TOKEN; return '`';
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 274 "ast.l"
TOKEN; return '$';
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 275 "ast.l"
TOKEN; return '\'';
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 276 "ast.l"
TOKEN; yylval.Identifier = strdup(yytext); lex_collect(yylval.Identifier); return ID;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 277 "ast.l"
TOKEN; yylval.Identifier = strdup(yytext); lex_collect(yylval.Identifier); return GID;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 278 "ast.l"
yparser()->column += 1;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 281 "ast.l"
ECHO;
	YY_BREAK
#line 1680 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 330 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 330 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 329);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 281 "ast.l"



int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

/* Comment */
static void comment(void)
{
    char c;
    ast_Parser p = yparser();

    while ((c = input()) && (c != EOF) && (c != '\n')) {
    }

    if (c == EOF) {
        void ast_Parser_error(ast_Parser p, corto_string fmt, ...);
        ast_Parser_error(p, "end of file encountered in comment");
        exit(1);
    } else {
        unput('\n');
    }
}

static unsigned int white_count(char* line) {
    unsigned int count = 0;
    while (*line == ' ') {
        count++;
        line++;
    }
    return count;
}

static int process_indent(char* line) {
    int result = 0;

    if (nesting || trailing) {
        /* Ignore indents while nested. */
        return 0;
    }

    unsigned int indent = white_count(line);

    if (indent == indent_stack[level]) {
        return 0;
    }

    if (indent > indent_stack[level]) {
        indent_stack[++level] = indent;
        return 1;
    }

    while (indent < indent_stack[level]) {
        result--;
        --level;
    }

    return result;
}

static void fast_doIndents(int indent) {
    if (indent > 0) {
        unput(' ');
        unput('i');
        unput('#');
    } else if (indent) {
        while (indent) {
            unput(' ');
            unput('d');
            unput('#');
            indent++;
        }
    }
}

