language: c

sudo: false

install:
  - cd ..
  - mkdir cortoproject
  - mv corto-language cortoproject/corto-language
  - cd cortoproject
  - git clone https://github.com/cortoproject/corto.git
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/io.git
  - git clone https://github.com/cortoproject/cortodoc.git
  - git clone https://github.com/cortoproject/test.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding xml corto-language io cortodoc test)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile

script:
  - source corto/configure
  - rake
  - rake test
