/* _meta.h
 *
 * Loads objects in object store.
 * This file contains generated code. Do not modify!
 */

#ifndef CORTO_PARSER_META_H
#define CORTO_PARSER_META_H

#include <corto/corto.h>
#include <corto/parser/_interface.h>

#ifdef __cplusplus
extern "C" {
#endif

CORTO_PARSER_EXPORT extern corto_package corto_parser_o;
CORTO_PARSER_EXPORT extern corto_class parser_BaseParser_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseParser_displayRecognitionError_o;
CORTO_PARSER_EXPORT extern corto_method parser_BaseParser_parse_o;
CORTO_PARSER_EXPORT extern corto_method parser_BaseParser_parseFile_o;
CORTO_PARSER_EXPORT extern corto_member parser_BaseParser_programReturn_o;
CORTO_PARSER_EXPORT extern corto_member parser_BaseParser_success_o;
CORTO_PARSER_EXPORT extern corto_class parser_BaseVisitor_o;
CORTO_PARSER_EXPORT extern corto_method parser_BaseVisitor_construct_o;
CORTO_PARSER_EXPORT extern corto_method parser_BaseVisitor_destruct_o;
CORTO_PARSER_EXPORT extern corto_member parser_BaseVisitor_parser_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visit_o;
CORTO_PARSER_EXPORT extern corto_class parser_BinaryExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_member parser_BinaryExpressionNode_left_o;
CORTO_PARSER_EXPORT extern corto_member parser_BinaryExpressionNode_operator_o;
CORTO_PARSER_EXPORT extern corto_member parser_BinaryExpressionNode_right_o;
CORTO_PARSER_EXPORT extern corto_class parser_CommaExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_member parser_CommaExpressionNode_expressions_o;
CORTO_PARSER_EXPORT extern corto_class parser_ConditionalExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_member parser_ConditionalExpressionNode_condition_o;
CORTO_PARSER_EXPORT extern corto_member parser_ConditionalExpressionNode_falseValue_o;
CORTO_PARSER_EXPORT extern corto_member parser_ConditionalExpressionNode_trueValue_o;
CORTO_PARSER_EXPORT extern corto_list parser_ExpressionList_o;
CORTO_PARSER_EXPORT extern corto_class parser_ExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_class parser_ExpressionStatementNode_o;
CORTO_PARSER_EXPORT extern corto_member parser_ExpressionStatementNode_expression_o;
CORTO_PARSER_EXPORT extern corto_class parser_Node_o;
CORTO_PARSER_EXPORT extern corto_member parser_Node_column_o;
CORTO_PARSER_EXPORT extern corto_member parser_Node_line_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitBinaryExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitCommaExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitConditionalExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_class parser_StatementNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitStatementNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitExpressionStatementNode_o;
CORTO_PARSER_EXPORT extern corto_list parser_StatementList_o;
CORTO_PARSER_EXPORT extern corto_class parser_PrintVisitor_o;
CORTO_PARSER_EXPORT extern corto_member parser_PrintVisitor_buffer_o;
CORTO_PARSER_EXPORT extern corto_member parser_PrintVisitor_level_o;
CORTO_PARSER_EXPORT extern corto_class parser_ProgramNode_o;
CORTO_PARSER_EXPORT extern corto_member parser_ProgramNode_statements_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_BaseVisitor_visitProgramNode_o;
CORTO_PARSER_EXPORT extern corto_method parser_PrintVisitor_construct_o;
CORTO_PARSER_EXPORT extern corto_method parser_PrintVisitor_destruct_o;
CORTO_PARSER_EXPORT extern corto_method parser_PrintVisitor_getText_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_PrintVisitor_visitBinaryExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_PrintVisitor_visitCommaExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_PrintVisitor_visitConditionalExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_PrintVisitor_visitExpressionNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_PrintVisitor_visitProgramNode_o;
CORTO_PARSER_EXPORT extern corto_virtual parser_PrintVisitor_visitStatementNode_o;
CORTO_PARSER_EXPORT extern corto_class parser_SimpleParser_o;
CORTO_PARSER_EXPORT extern corto_method parser_SimpleParser_displayRecognitionError_o;
CORTO_PARSER_EXPORT extern corto_member parser_SimpleParser_errors_o;
CORTO_PARSER_EXPORT extern corto_list corto_stringList_o;

#ifdef __cplusplus
}
#endif
#endif

