/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : Cortolang.g
 *     -                            On : 2016-05-31 20:36:38
 *     -                for the parser : CortolangParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
CortolangParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pCortolangParser, which is returned from a call to CortolangParserNew().
 *
 * The methods in pCortolangParser are  as follows:
 *
 *  - 
 parser_ProgramNode ___
      pCortolangParser->program(pCortolangParser)
 *  - 
 parser_StatementNode ___
      pCortolangParser->statement(pCortolangParser)
 *  - 
 void
      pCortolangParser->declarativeStatement(pCortolangParser)
 *  - 
 parser_StatementNode ___
      pCortolangParser->simpleStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->compositeStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->block(pCortolangParser)
 *  - 
 void
      pCortolangParser->declarationExt(pCortolangParser)
 *  - 
 void
      pCortolangParser->declarationNameList(pCortolangParser)
 *  - 
 void
      pCortolangParser->declarationName(pCortolangParser)
 *  - 
 void
      pCortolangParser->initializer(pCortolangParser)
 *  - 
 void
      pCortolangParser->scopeOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->scope_(pCortolangParser)
 *  - 
 void
      pCortolangParser->functionDeclaration(pCortolangParser)
 *  - 
 void
      pCortolangParser->functionArguments(pCortolangParser)
 *  - 
 void
      pCortolangParser->functionArgument(pCortolangParser)
 *  - 
 void
      pCortolangParser->ifStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->elseStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->whileStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->breakStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->continueStatement(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->expression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->assignmentExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->simpleCommaExpression(pCortolangParser)
 *  - 
 void
      pCortolangParser->fullCommaExpression(pCortolangParser)
 *  - 
 void
      pCortolangParser->commaExpressionElem(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->conditionalExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->logicOrExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->logicAndExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->equalityExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->comparisonExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->bitOrExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->bitXorExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->bitAndExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->shiftExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->addExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->multExpression(pCortolangParser)
 *  - 
 parser_ExpressionNode ___
      pCortolangParser->unaryExpression(pCortolangParser)
 *  - 
 void
      pCortolangParser->postfixExpression(pCortolangParser)
 *  - 
 void
      pCortolangParser->atomExpression(pCortolangParser)
 *  - 
 void
      pCortolangParser->anonymousObject(pCortolangParser)
 *  - 
 void
      pCortolangParser->observerStatement(pCortolangParser)
 *  - 
 void
      pCortolangParser->eventMask(pCortolangParser)
 *  - 
 void
      pCortolangParser->eventFlag(pCortolangParser)
 *  - 
 void
      pCortolangParser->eventBaseFlag(pCortolangParser)
 *  - 
 void
      pCortolangParser->eventScopeFlag(pCortolangParser)
 *  - 
 void
      pCortolangParser->assignmentOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->eqOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->comparisonOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->shiftOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->addOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->multOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->unaryOp(pCortolangParser)
 *  - 
 void
      pCortolangParser->postfixOperation(pCortolangParser)
 *  - 
 void
      pCortolangParser->functionCall(pCortolangParser)
 *  - 
 void
      pCortolangParser->memberAccess(pCortolangParser)
 *  - 
 void
      pCortolangParser->elementAccess(pCortolangParser)
 *  - 
 void
      pCortolangParser->postScopeOperator(pCortolangParser)
 *  - 
 void
      pCortolangParser->preScopeOperator(pCortolangParser)
 *  - 
 void
      pCortolangParser->constant(pCortolangParser)
 *  - 
 void
      pCortolangParser->identifier(pCortolangParser)
 *  - 
 void
      pCortolangParser->typeLabel(pCortolangParser)
 *  - 
 void
      pCortolangParser->literal(pCortolangParser)
 *  - 
 void
      pCortolangParser->booleanLiteral(pCortolangParser)
 * 
 * 
 * 
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_CortolangParser_H
#define _CortolangParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#include "CustomParser.hpp"


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct CortolangParser_Ctx_struct CortolangParser, * pCortolangParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */


/** Context tracking structure for 
CortolangParser

 */
struct CortolangParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     parser_ProgramNode ___
     (*program)	(struct CortolangParser_Ctx_struct * ctx);

     parser_StatementNode ___
     (*statement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*declarativeStatement)	(struct CortolangParser_Ctx_struct * ctx);

     parser_StatementNode ___
     (*simpleStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*compositeStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*block)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*declarationExt)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*declarationNameList)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*declarationName)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*initializer)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*scopeOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*scope_)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*functionDeclaration)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*functionArguments)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*functionArgument)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*ifStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*elseStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*whileStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*breakStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*continueStatement)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*expression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*assignmentExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*simpleCommaExpression)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*fullCommaExpression)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*commaExpressionElem)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*conditionalExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*logicOrExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*logicAndExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*equalityExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*comparisonExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*bitOrExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*bitXorExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*bitAndExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*shiftExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*addExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*multExpression)	(struct CortolangParser_Ctx_struct * ctx);

     parser_ExpressionNode ___
     (*unaryExpression)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*postfixExpression)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*atomExpression)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*anonymousObject)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*observerStatement)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*eventMask)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*eventFlag)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*eventBaseFlag)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*eventScopeFlag)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*assignmentOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*eqOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*comparisonOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*shiftOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*addOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*multOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*unaryOp)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*postfixOperation)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*functionCall)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*memberAccess)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*elementAccess)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*postScopeOperator)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*preScopeOperator)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*constant)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*identifier)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*typeLabel)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*literal)	(struct CortolangParser_Ctx_struct * ctx);

     void
     (*booleanLiteral)	(struct CortolangParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred1_Cortolang)	(struct CortolangParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred2_Cortolang)	(struct CortolangParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred3_Cortolang)	(struct CortolangParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred4_Cortolang)	(struct CortolangParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred5_Cortolang)	(struct CortolangParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct CortolangParser_Ctx_struct * ctx);
    void	    (*free)   (struct CortolangParser_Ctx_struct * ctx);

    struct parser_data* parser_data;

};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pCortolangParser CortolangParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pCortolangParser CortolangParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define AMPERSAND      4
#define ASTERISK      5
#define BITAND_EQUALS      6
#define BITOR_EQUALS      7
#define BITXOR_EQUALS      8
#define CHARACTER      9
#define CIRCUMFLEX      10
#define COLON      11
#define COMMA      12
#define DEDENT      13
#define DIGIT      14
#define DIV_EQUAL      15
#define DOT      16
#define DOUBLE_COLON      17
#define EMARK      18
#define EQUAL      19
#define EQUALS      20
#define ESC      21
#define GID      22
#define GREATER_THAN      23
#define GREATER_THAN_EQUAL      24
#define IMPLICIT_LINE_WHITESPACE      25
#define INDENT      26
#define INTEGER      27
#define KW_AND      28
#define KW_BREAK      29
#define KW_CONTINUE      30
#define KW_DECLARE      31
#define KW_DEFINE      32
#define KW_DESTRUCT      33
#define KW_ELSE      34
#define KW_FALSE      35
#define KW_FOR      36
#define KW_IF      37
#define KW_ON      38
#define KW_OR      39
#define KW_SCOPE      40
#define KW_SELF      41
#define KW_SYNCHRONIZED      42
#define KW_TREE      43
#define KW_TRUE      44
#define KW_UPDATE      45
#define KW_WAIT      46
#define KW_WHILE      47
#define LBRACE      48
#define LBRACK      49
#define LEADING_WHITESPACE      50
#define LESS_THAN      51
#define LESS_THAN_EQUAL      52
#define LETTER_UNDERSCORE      53
#define LPAREN      54
#define LSHIFT      55
#define LSHIFT_EQUALS      56
#define MINUS      57
#define MINUS_EQUAL      58
#define NEWLINE      59
#define NOT_EQUALS      60
#define PIPE      61
#define PLUS      62
#define PLUS_EQUAL      63
#define QMARK      64
#define RBRACE      65
#define RBRACK      66
#define RPAREN      67
#define RSHIFT      68
#define RSHIFT_EQUALS      69
#define SLASH      70
#define STRING      71
#define TILDE      72
#define TIMES_EQUAL      73
#define TRIPLE_COLON      74
#define VALID_NAME      75
#define WHITESPACE      76
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for CortolangParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
