/* TestPrintVisitor.h
 *
 * This file contains generated code. Do not modify!
 */

#ifndef TEST_TESTPRINTVISITOR_H
#define TEST_TESTPRINTVISITOR_H

#include <corto/corto.h>
#include <_interface.h>
#include <_type.h>
#include <_api.h>
#include <_meta.h>

#ifdef __cplusplus
extern "C" {
#endif


TEST_EXPORT corto_void _test_TestPrintVisitor_test_addExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_addExpression1(_this) _test_TestPrintVisitor_test_addExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_bitAndExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_bitAndExpression1(_this) _test_TestPrintVisitor_test_bitAndExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_bitOrExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_bitOrExpression1(_this) _test_TestPrintVisitor_test_bitOrExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_bitOrExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_bitOrExpression2(_this) _test_TestPrintVisitor_test_bitOrExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_callExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_callExpression1(_this) _test_TestPrintVisitor_test_callExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_callExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_callExpression2(_this) _test_TestPrintVisitor_test_callExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_comparisonExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_comparisonExpression1(_this) _test_TestPrintVisitor_test_comparisonExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_comparisonExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_comparisonExpression2(_this) _test_TestPrintVisitor_test_comparisonExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_ConditionalExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_ConditionalExpression1(_this) _test_TestPrintVisitor_test_ConditionalExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_ConditionalExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_ConditionalExpression2(_this) _test_TestPrintVisitor_test_ConditionalExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_elementExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_elementExpression1(_this) _test_TestPrintVisitor_test_elementExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_elementExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_elementExpression2(_this) _test_TestPrintVisitor_test_elementExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_equalityExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_equalityExpression1(_this) _test_TestPrintVisitor_test_equalityExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_equalityExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_equalityExpression2(_this) _test_TestPrintVisitor_test_equalityExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_functionDeclaration1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_functionDeclaration1(_this) _test_TestPrintVisitor_test_functionDeclaration1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_functionDeclaration2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_functionDeclaration2(_this) _test_TestPrintVisitor_test_functionDeclaration2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_functionDeclaration3(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_functionDeclaration3(_this) _test_TestPrintVisitor_test_functionDeclaration3(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_logicAndExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_logicAndExpression1(_this) _test_TestPrintVisitor_test_logicAndExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_logicAndExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_logicAndExpression2(_this) _test_TestPrintVisitor_test_logicAndExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_logicOrExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_logicOrExpression1(_this) _test_TestPrintVisitor_test_logicOrExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_logicOrExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_logicOrExpression2(_this) _test_TestPrintVisitor_test_logicOrExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_memberExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_memberExpression1(_this) _test_TestPrintVisitor_test_memberExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_memberExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_memberExpression2(_this) _test_TestPrintVisitor_test_memberExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_multExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_multExpression1(_this) _test_TestPrintVisitor_test_multExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration1(_this) _test_TestPrintVisitor_test_objectDeclaration1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration10(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration10(_this) _test_TestPrintVisitor_test_objectDeclaration10(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration11(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration11(_this) _test_TestPrintVisitor_test_objectDeclaration11(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration2(_this) _test_TestPrintVisitor_test_objectDeclaration2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration3(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration3(_this) _test_TestPrintVisitor_test_objectDeclaration3(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration4(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration4(_this) _test_TestPrintVisitor_test_objectDeclaration4(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration5(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration5(_this) _test_TestPrintVisitor_test_objectDeclaration5(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration6(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration6(_this) _test_TestPrintVisitor_test_objectDeclaration6(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration7(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration7(_this) _test_TestPrintVisitor_test_objectDeclaration7(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration8(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration8(_this) _test_TestPrintVisitor_test_objectDeclaration8(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_objectDeclaration9(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_objectDeclaration9(_this) _test_TestPrintVisitor_test_objectDeclaration9(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_shiftExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_shiftExpression1(_this) _test_TestPrintVisitor_test_shiftExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_unaryExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_unaryExpression1(_this) _test_TestPrintVisitor_test_unaryExpression1(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_unaryExpression2(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_unaryExpression2(_this) _test_TestPrintVisitor_test_unaryExpression2(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_visitorAssignment(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_visitorAssignment(_this) _test_TestPrintVisitor_test_visitorAssignment(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_visitorAtom(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_visitorAtom(_this) _test_TestPrintVisitor_test_visitorAtom(test_TestPrintVisitor(_this))

TEST_EXPORT corto_void _test_TestPrintVisitor_test_visitorCommaExpression1(
    test_TestPrintVisitor _this);
#define test_TestPrintVisitor_test_visitorCommaExpression1(_this) _test_TestPrintVisitor_test_visitorCommaExpression1(test_TestPrintVisitor(_this))

#ifdef __cplusplus
}
#endif
#endif

